"use client"
import { useSession } from 'next-auth/react'
import '../../styles/globals.css'
import Provider from './SessionProvider'
import Nav from '../../components/LayoutComponents/nav.component'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <Provider>
          <body>
            <Nav></Nav>
            {children}
          </body>
      </Provider>
    </html>
  )
}
